### DISCUSSION TITLE
How do I release?

### DISCUSSION THREAD

**Discussion by ceceayo** [browniebroke/pypackage-template#794] [Q&A] [answered]
So, I have created a project with this template, located at [github/ceceayo/komis](https://github.com/ceceayo/komis), and I can not find how to release a stable version. I have figured the version number is generated automatically based on the commit message. By starting my commit message with `feat!: ...`, my version was increased from `0.0.0` to `1.0.0-rc.1`. What should I do to go from `1.0.0-rc.1` to a real `1.0.0`?

**Comment by browniebroke** [comment, marked as answer]
I think it's because your main branch is called "master" while the template assumes that you'll use "main". You'll need to change this bit: 

https://github.com/ceceayo/komis/blob/71fb472ddf11b551a5728ce0a2d15b84189b5be5/pyproject.toml#L66-L71

To the following:

```toml
[tool.semantic_release.branches.master]
match = "master"

[tool.semantic_release.branches.noop]
match = "(?!master$)"
prerelease = true
```
